version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: market_data_postgres
    environment:
      POSTGRES_DB: market_data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d market_data"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 