"""Initial migration

Revision ID: 6c3e2b197283
Revises: 
Create Date: 2025-06-19 19:35:32.312049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3e2b197283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polling_job_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('alpha_vantage', 'yahoo_finance', 'finnhub', name='providerenum'), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'pending', 'running', 'completed', 'failed', name='pollingjobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_market_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('alpha_vantage', 'yahoo_finance', 'finnhub', name='providerenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['polling_job_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_market_data_symbol'), 'raw_market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_raw_market_data_timestamp'), 'raw_market_data', ['timestamp'], unique=False)
    op.create_index('ix_raw_symbol_ts', 'raw_market_data', ['symbol', 'timestamp'], unique=False)
    op.create_table('price_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('alpha_vantage', 'yahoo_finance', 'finnhub', name='providerenum'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('raw_data_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_market_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_points_symbol'), 'price_points', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_points_timestamp'), 'price_points', ['timestamp'], unique=False)
    op.create_index('ix_price_symbol_ts', 'price_points', ['symbol', 'timestamp'], unique=False)
    op.create_table('symbol_averages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moving_average', sa.Float(), nullable=False),
    sa.Column('calculation_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price_count', sa.Integer(), nullable=False),
    sa.Column('trigger_price_point_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trigger_price_point_id'], ['price_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'timestamp', name='uq_symbol_interval_timestamp')
    )
    op.create_index('ix_ma_symbol_interval_ts', 'symbol_averages', ['symbol', 'interval', 'timestamp'], unique=False)
    op.create_index(op.f('ix_symbol_averages_symbol'), 'symbol_averages', ['symbol'], unique=False)
    op.create_index(op.f('ix_symbol_averages_timestamp'), 'symbol_averages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_averages_timestamp'), table_name='symbol_averages')
    op.drop_index(op.f('ix_symbol_averages_symbol'), table_name='symbol_averages')
    op.drop_index('ix_ma_symbol_interval_ts', table_name='symbol_averages')
    op.drop_table('symbol_averages')
    op.drop_index('ix_price_symbol_ts', table_name='price_points')
    op.drop_index(op.f('ix_price_points_timestamp'), table_name='price_points')
    op.drop_index(op.f('ix_price_points_symbol'), table_name='price_points')
    op.drop_table('price_points')
    op.drop_index('ix_raw_symbol_ts', table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_timestamp'), table_name='raw_market_data')
    op.drop_index(op.f('ix_raw_market_data_symbol'), table_name='raw_market_data')
    op.drop_table('raw_market_data')
    op.drop_table('polling_job_configs')
    # ### end Alembic commands ###
